### ISSUE TITLE
[Bug] wrong calc lapses in State=Review

### ISSUE THREAD

**Issue by ishiko732** [MayorNG/csharp_fsrs#1]
https://github.com/MayorNG/csharp_fsrs/blob/95f67878f0a3608f4ad63e321232165ec0c80f6f/csharp-fsrs/Scheduler.cs#L86-L91
这段代码有点问题，在State.Review情况下，需要改变`Again`卡片的`lapses`,这`lapses`参数便于设计暂停卡片feature。

`ts-fsrs`因为有了`afterHandler`来处理后续逻辑，暂停卡片的feature目前没计划内置，`ts-fsrs-demo`暂停卡片实现代码：
https://github.com/ishiko732/ts-fsrs-demo/blob/38d8fd198e4b3c3149a603b31210039da62b0a43/src/vendor/fsrsToPrisma/handler.ts#L51-L74

**Comment by MayorNG** [comment]
感谢指正！
lapses不会增加的BUG已经如下得到修复
https://github.com/MayorNG/csharp_fsrs/blob/0fcaa4cca7a22e44865311ff9193a409f3dea48f/csharp-fsrs/Scheduler.cs#L86-L92

另外,
关于如何实现类似`afterHandler`的自定义后续逻辑处理，我会在后面做做进一步研究

**Comment by ishiko732** [comment]
> 关于如何实现类似`afterHandler`的自定义后续逻辑处理，我会在后面做做进一步研究

C#可能不需要这个东西，这个是在typescript才有（我需要兼容多种不同类型的日期类型）。 你可能需要修改repeat，rollback等方法输入，以便支持传入继承Card的子类。 例如typescript中的：`<T extends CardInput | Card>`
https://github.com/open-spaced-repetition/ts-fsrs/blob/cb59bf1368f6dcd3d7bb261499f3bd675aafd3f8/src/fsrs/fsrs.ts#L372-L375

**Comment by ishiko732** [comment]
> 以便支持传入继承Card的子类

因为绝大多数情况下，Card会存在id，但算法库不会强制使用id这个字段（变量），所以传入子类，并传出子类可以很方便使用算法库。
